First plot data points on a scatter plot to see if Linear Regression model can be applied.
If yes then build a model that can answer the following questions:
1) Predict price of a Mercedes Benz that is 4 years old with mileage 45000
2) Predict price of a BMW X5 that is 7 years old with mileage 86000
3) Tell me the accuracy of your model

In [194]:
import pandas as pd
import numpy as np

In [195]:
df = pd.read_csv('carprices.csv')
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [196]:
df.nunique()

Car Model         3
Mileage          12
Sell Price($)    13
Age(yrs)          7
dtype: int64

In [197]:
df.columns

Index(['Car Model', 'Mileage', 'Sell Price($)', 'Age(yrs)'], dtype='object')

In [198]:
dummy = pd.get_dummies(df['Car Model'])
dummy

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [199]:
merged = pd.concat([df, dummy], axis = 1)
merged

Car Model  Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  \
0                  BMW X5    69000          18000         6        0       1   
1                  BMW X5    35000          34000         3        0       1   
2                  BMW X5    57000          26100         5        0       1   
3                  BMW X5    22500          40000         2        0       1   
4                  BMW X5    46000          31500         4        0       1   
5                 Audi A5    59000          29400         5        1       0   
6                 Audi A5    52000          32000         5        1       0   
7                 Audi A5    72000          19300         6        1       0   
8                 Audi A5    91000          12000         8        1       0   
9   Mercedez Benz C class    67000          22000         6        0       0   
10  Mercedez Benz C class    83000          20000         7        0       0   
11  Mercedez Benz C class    79000          21000         7        0       0   
12  Mercedez Benz C class    59000          33000         5        0       0   

    Mercedez Benz C class  
0                       0  
1                       0  
2                       0  
3                       0  
4                       0  
5                       0  
6                       0  
7                       0  
8                       0  
9                       1  
10                      1  
11                      1  
12                      1

In [200]:
droped = merged.drop(['Car Model', 'Mercedez Benz C class'], axis = 1)
droped

Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6        0       1
1     35000          34000         3        0       1
2     57000          26100         5        0       1
3     22500          40000         2        0       1
4     46000          31500         4        0       1
5     59000          29400         5        1       0
6     52000          32000         5        1       0
7     72000          19300         6        1       0
8     91000          12000         8        1       0
9     67000          22000         6        0       0
10    83000          20000         7        0       0
11    79000          21000         7        0       0
12    59000          33000         5        0       0

In [201]:
final = droped.drop(['Sell Price($)'], axis = 1)
X = final
X

Mileage  Age(yrs)  Audi A5  BMW X5
0     69000         6        0       1
1     35000         3        0       1
2     57000         5        0       1
3     22500         2        0       1
4     46000         4        0       1
5     59000         5        1       0
6     52000         5        1       0
7     72000         6        1       0
8     91000         8        1       0
9     67000         6        0       0
10    83000         7        0       0
11    79000         7        0       0
12    59000         5        0       0

In [202]:
y = df['Sell Price($)']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [203]:
from sklearn import linear_model
reg = linear_model.LinearRegression()

In [204]:
reg.fit(X.values, y.values)

LinearRegression()

In [205]:
reg.coef_, reg.intercept_

(array([-3.70122094e-01, -1.33245363e+03, -2.45354074e+03, -6.73820733e+03]),
 58976.62596853723)

1. Predict price of a Mercedez Benz C class that is 4 years old with mileage 45000.
2. Predict price of a BMW X 5 that is 7 years old with mileage 86000.
3. Tell me the score (accuracy) of your model.
Hint: Use LinearRegression().score()

In [206]:
reg.predict([[45000, 4, 0, 0]]), reg.predict([[86000, 7, 0, 1]]), reg.score(X.values, y.values)

(array([36991.31721061]), array([11080.74313219]), 0.9417050937281083)

In [207]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dfle = df
dfle

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [208]:
dfle['Car Model'] = le.fit_transform(dfle['Car Model'])
dfle

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [209]:
X, y = dfle[['Car Model', 'Mileage', 'Age(yrs)']].values, dfle['Sell Price($)'].values
X, y

(array([[    1, 69000,     6],
        [    1, 35000,     3],
        [    1, 57000,     5],
        [    1, 22500,     2],
        [    1, 46000,     4],
        [    0, 59000,     5],
        [    0, 52000,     5],
        [    0, 72000,     6],
        [    0, 91000,     8],
        [    2, 67000,     6],
        [    2, 83000,     7],
        [    2, 79000,     7],
        [    2, 59000,     5]], dtype=int64),
 array([18000, 34000, 26100, 40000, 31500, 29400, 32000, 19300, 12000,
        22000, 20000, 21000, 33000], dtype=int64))

In [210]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [211]:
ct = ColumnTransformer([('Car Model', OneHotEncoder(), [0])], remainder='passthrough')
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('Car Model', OneHotEncoder(), [0])])

In [212]:
type(X), type(y)

(numpy.ndarray, numpy.ndarray)

In [213]:
X = ct.fit_transform(X)
X

array([[0.00e+00, 1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [214]:
X = X[:,1:]
X

array([[1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [215]:
from sklearn.model_selection import train_test_split

In [216]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 10)

In [217]:
X_train.shape, X_test.shape

((10, 4), (3, 4))

In [218]:
X_train, y_train

(array([[0.0e+00, 0.0e+00, 5.2e+04, 5.0e+00],
        [0.0e+00, 0.0e+00, 9.1e+04, 8.0e+00],
        [1.0e+00, 0.0e+00, 5.7e+04, 5.0e+00],
        [0.0e+00, 1.0e+00, 5.9e+04, 5.0e+00],
        [0.0e+00, 0.0e+00, 5.9e+04, 5.0e+00],
        [0.0e+00, 1.0e+00, 8.3e+04, 7.0e+00],
        [1.0e+00, 0.0e+00, 3.5e+04, 3.0e+00],
        [1.0e+00, 0.0e+00, 6.9e+04, 6.0e+00],
        [1.0e+00, 0.0e+00, 4.6e+04, 4.0e+00],
        [0.0e+00, 1.0e+00, 6.7e+04, 6.0e+00]]),
 array([32000, 12000, 26100, 33000, 29400, 20000, 34000, 18000, 31500,
        22000], dtype=int64))

In [219]:
X_test, y_test

(array([[1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
        [0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
        [0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00]]),
 array([40000, 19300, 21000], dtype=int64))

In [220]:
reg.fit(X_train, y_train)

LinearRegression()

In [221]:
reg.predict([[0, 1, 45000, 4]]), reg.predict([[1, 0, 86000, 7]]), reg.score(X_test, y_test)

(array([36871.03077103]), array([12537.34643734]), 0.8675370464375844)